# -*- coding: utf-8 -*-
"""Assignments.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DQMoCxhmcZD2sYemVyTPBWM_gOaxLXDF
"""

#QUES1) If input is 1 print date of the computer if input is 2 create folder

import datetime
import os
current_date = datetime.date.today()
user_input = input("Enter your choice: ")
if user_input == "1":
    print("The current date is", current_date)
elif user_input == "2":
    folder_name = input("Enter the folder name: ")
    desktop_path = os.path.join(os.path.expanduser("~"), "Desktop")
    folder_path = os.path.join(desktop_path, folder_name)
    os.makedirs(folder_path)
    print("The folder has been created successfully!")
elif user_input == "3":
    file_name = input("Enter the file name: ")
    desktop_path = os.path.join(os.path.expanduser("~"), "Desktop")
    file_path = os.path.join(desktop_path, file_name)
    open(file_path, "w").close()

    print("The file has been created successfully!")
elif user_input == "4":
    os.system("shutdown /s /t 0")
else:
    print("Invalid input!")

#Ques2) Take input from user on number of units in integer.For starting 10 units price is Rs.50 each.For the next 20 units the price will be Rs.20 each.For rest units price will be Rs.10 each.Calculate total price.
units = int(input("Enter the number of units: "))
if units <= 10:
    tp= units * 50
elif units <= 30:
    tp= 10*50+(units-10)*20
else:
    tp=10*50+20*20+(units-30)*10
print("Total price for", units, "units is Rs.",tp)

#Ques3)Take 3 numbers as inputs as the sides of the triangle from the user.Check whether the triangle will form or not.
a = float(input("Enter side one: "))
b = float(input("Enter side second: "))
c = float(input("Enter side third: "))
if a+b>c and a+c>b and b+c>a:
    print("Yes, a triangle can be formed with sides of length",a,",",b,",and",c)
else:
    print("No, a triangle cannot be formed with sides of length",a,",",b,",and",c)

#Ques4)Take two number from the user and check whether both the number are divisible by 6 or not.
num1 = int(input("Enter the first number: "))
num2 = int(input("Enter the second number: "))
if num1 % 6 == 0 and num2 % 6 == 0:
    print("Both numbers", num1, "and", num2, "are divisible by 6.")
elif num1%6==0 or num2%6!=0:
    print("At least one of the numbers is not divisible by 6.")

#Ques5)Make a pattern
1
12
123
1234
12345
for i in range(1, 6):
    for j in range(1, i + 1):
        print(j, end="")
    print("")

#Ques6)Make a pattern:
'''1
2 3
4 5 6
7 8 9 10'''
count=1
for i in range(1, 5):
    for j in range(0,i):
        print(count, end=" ")
        count+= 1
    print("")

#Ques7)Make a pattern:
'''10
9 8
7 6 5
4 3 2 1'''
num = 10
for i in range(0,4):
    for j in range(0,i+1):
        print(num, end=' ')
        num-=1
    print("\r")

#Ques8)Make a pattern
'''A
A B
A B C
A B C D'''
for i in range(1, 5):
    for j in range(65, 65 + i):
        print(chr(j), end=" ")
    print()

#Ques9)Make a pattern:
'''A
B C
D E F
G H I J'''
count=65
for i in range(1,5):
    for j in range(i):
        print(chr(count), end=" ")
        count+= 1
    print()

#Ques10)Make a pattern:
'''Z
X V
T R P'''
count=90
for i in range(0,3):
    for j in range(0,i+1):
        print(chr(count), end=" ")
        count=count-2
    print()

#Ques11)Check prime:
num = int(input("Enter a number: "))
if num > 1:
    for i in range(2, num):
        if num % i == 0:
            print(num, "is prime")
            break
    else:
        print(num, "is prime")
else:
    print(num,"is not prime")

