# -*- coding: utf-8 -*-
"""AssignmentMay11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HXRWPtW5bRy4NpFvmjIp3jDxSPhJZvMm
"""

#Ques1)Make a pattern:
'''1***
23**
456*'''
num = 1
for i in range(1, 4):
    for j in range(i):
        print(num, end="")
        num += 1
    print('*' * (4 - i))

#ques2)make a pattern:
'''ABCD1
ABC12
AB123
A1234'''
for i in range(5):
  for j in range(5):
    if i+j < 4:
      print(chr(65+j), end="")
    else:
      print(i+j-3, end="")
  print()

#QUES3)MAKE A PATTERN:
'''   A
     BC
    DEF
   GHIJ'''
ascii = 65
for i in range(0,4):
    for j in range(0,3-i):
        print(" ", end="")
    for j in range(0,i+1):
        print(chr(ascii), end="")
        ascii += 1
    print()

#ques4)make a pattern:
'''*****
    ***
     *'''
stars = 5
for i in range(0,3):
    print(" " * i, end="")
    print("*" * stars)
    stars -= 2

#ques5)make a pattern:
'''A1
BC23
DEF456
GHIJ78910
'''
ascii= 65
count= 1
for i in range(4):
    for j in range(i + 1):
        print(chr(ascii), end="")
        ascii+= 1
    for k in range(i + 1):
        print(count, end="")
        count+= 1
    print()

