# -*- coding: utf-8 -*-
"""Day4Assign.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GCIhKiLdVBG6pgXLbnPFXH2m7Had23C8
"""

#ques1)
temp= [21, 23, 18, 22, 19, 34, 24, 35]
fahtemp = list(map(lambda c: (c * 9/5) + 32,temp))
print("Temperatures in Fahrenheit:",fahtemp)

#ques2)
numbers = [25, 28, 26, 4000, 27, 31, 5, 28, 29, 30, 34, 8, 32, 33, 35, 32, 37, 36, 40, 38, 39, 95]
new= [num for num in numbers if 25 <= num <= 40]
print("Numbers in sequence:",new)

#ques3)
mylist = [3, 5, 2, 6, 8, 3, 18, 5, 3, 44, 21, 4, 18, 2]
new= []
for i in mylist:
    if i not in new:
        new.append(i)
print(new)

#ques4)
mylist = [3, 5, 2, 3, 8, 3, 2, 5, 3,4, 21, 4, 18, 2]
new= []
for i in mylist:
    if i not in new:
        new.append(i)
print(new)

#ques5)
def palindrome(s):
    s = s.lower()
    s = ''.join(char for char in s if char.isalnum())
    return s == s[::-1]
string= input("Enter a string: ")
if palindrome(string):
    print("Yes!palindrome.")
else:
    print("Not!palindrome.")



