# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14RwxrENiKNdlzRsdfeSUHakKrW_Bd9SZ
"""

state="RAJASTHAN"
state[0:4:-1]
state[-1:4:-1]
#range(start,stop,[step=1])
for i in range(1,5):
  print(i)

for i in range (1,5):
  print(i)

for i in range(1,8,3):
  print(i)

for num in range(97,18,-1):
  if num % 5==0 and num % 7==0:
    print(num)
  else:
    break

for i in "HELLO":
  print(i)

data="hello"
len(data)

data="hello"
len(data)

for index in range(0,5):
  print(index,data,data[index])

str="Rajasthan"
count=0
for i in str:
  count+=1
print(count)

str="equation"
count=0
for i in str:
  if i in "aeiou":
    count+=1
print(count)

str="equation"
count=0
for i in str:
  if i not in "aeiou":
    count+=1
print(count)

for i in range(1,6):
    print("hello",i)
    for j in range(1,5):
      print("tushar")

#****
#****
#****

for i in range(1,5):
  print(end="")
  print(" ")
  for j in range(1,5):
    print("*",end="")

for i in range(1,5):
  for j in range(1,5):
    print("*",end="")
  print("")

#ques2
for i in range (1,5):
  for j in range(1,6):
    print(j,end="")
  print("")

#ques3
for i in range (1,5):
  for j in range(5,0,-1):
    print(j,end="")
  print("")

#ques1
for i in range (1,6):
  for j in range(1,5):
    print(i,end="")
  print("")

#ques4
for i in range (1,6):
  for j in range(1,i+1):
    print("*",end="")
  print("")

#quesass1
for i in range (1,6):
  for j in range(1,i+1):
    print(j,end="")
  print("")

#ques4
for i in range (1,6):
  for j in range(i,5):
    print("*",end="")
  print("")

#password validation
password=input("enter password: ")
if len(password)<=15 and len(password)>=5:
  if password== '#' or password=="@" or password=="!":
    if password.isupper()>=3:
      if password.islower()>=2:
        if password=="1234567890":
          print("valid")
        else:
          print("invalid")

num=int(input("ENTER A NUMBER TO CHECK WHETHER IT IS PRIME OR NOT: "))
if num<=1:
  print("NOT PRIME")
elif num>1:
  for i in range(2,num):
    if(num%i==0):
      print("NOT PRIME")
      break
    else:
      print("PRIME NUMBER")
      break
else:
  print("NON PRIME")

#quesass2
a=1
for i in range (1,6):
  for j in range(0,i):
    print(a,end="  ")
    a+=1
  print("")

for i in range (1,6):
  for j in range(i,j,-1):
    print(j,end="  ")
  print("")

